services:
  server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - JWT_SECRET=supersecretkey123
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
